name: '_CI Setup'

on:
    workflow_call:
        inputs:
            install-php:
                required: false
                type: boolean
                default: false
            install-composer:
                required: false
                type: boolean
                default: false

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  cache: 'npm'

            - name: Set up PHP
              if: ${{ inputs.install-php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: mbstring, intl, zip

            - name: Install root dependencies
              run: npm ci

            - name: Install Composer dependencies
              if: ${{ inputs.install-composer }}
              run: composer install --prefer-dist --no-progress

            - name: Upload workspace
              uses: actions/upload-artifact@v3
              with:
                  name: workspace
                  path: .
